# Use the official Bun image
FROM oven/bun:latest

# Set the working directory
WORKDIR /app

# Copy package.json, bun.lockb, and other dependencies first
COPY package*.json bun.lock ./

# Install dependencies
RUN bun install

# Copy the rest of the application files
COPY . .

# Expose the port Bun will run on
EXPOSE 3000

# Start the Bun app
CMD ["bun","run","dev"]